export const paths = {
    home: '/', 
    products: '/products',
    transaction: '/transaction',
    invoice: '/invoice',
    customer: '/customer',
    employee: '/employee',
    report: '/report',
    setting: '/setting',
    login: '/login',
    users: '/users',
    adminProfile: '/profile',
    category: '/category',
    supplier: '/supplier',
}